--------------------------------------------------------------------------------
-- SSOT DEC-DB-024 — privilégios DML (tabelas baseline homologação 2026-07-22)
-- Executar como UNMPORTCOM (owner)
-- Espelhado em database/ddl/007-create-grants.sql (greenfield)
--------------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON FEDERACAO               TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON SINGULAR                TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ENDERECO                TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTATO                 TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON AREA                    TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON EQUIPE                  TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON COLABORADOR             TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ONBOARDING_SOLICITACAO  TO UNMPORTCOM_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIA_DOCUMENTAL    TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PASTA                   TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DOCUMENTO               TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DOCUMENTO_VERSAO        TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ARQUIVO_BINARIO         TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMPARTILHAMENTO        TO UNMPORTCOM_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON PAPEL                   TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTH_SESSAO             TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAPEL_ATRIBUICAO        TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERMISSAO_PASTA         TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON SOLICITACAO_PERMISSAO   TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON REGISTRO_AUDITORIA      TO UNMPORTCOM_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON COMUNICADO              TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON NOTIFICACAO             TO UNMPORTCOM_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONFIGURACAO_PORTAL     TO UNMPORTCOM_APP_ROLE;
