--------------------------------------------------------------------------------
-- SSOT DEC-DB-024 — privilégios em sequences (baseline 2026-07-22)
-- Executar como UNMPORTCOM (owner)
--------------------------------------------------------------------------------

GRANT SELECT ON SQ_FEDERACAO_COD_FEDERACAO        TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_SINGULAR_COD_SINGULAR          TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_AREA_COD_AREA                  TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_EQUIPE_COD_EQUIPE              TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_COLABORADOR                    TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_ONBOARD_SOLIC                  TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_DOCUMENTO_COD_DOCUMENTO        TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_REG_AUDIT_COD_REG_AUDIT        TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_AUTH_SESSAO                    TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_COMUNICADO_COD_COMUNICADO      TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_NOTIFICACAO_COD_NOTIFICACAO    TO UNMPORTCOM_APP_ROLE;
GRANT SELECT ON SQ_CONFIG_PORT_COD_CONFIG_PORT      TO UNMPORTCOM_APP_ROLE;
