--------------------------------------------------------------------------------
-- Projeto : Portal de Comunicação
-- Arquivo : 901-validation.sql
-- Versão  : 1.2
--
-- Objetivo
--   Validar a instalação do schema UNMPORTCOM.
--
-- Contagens esperadas (baseline homologada 2026-07-22, DB-SYNC-99):
--   23 tabelas · 12 sequences · 95 índices
--   Constraints: 23 PK · 36 FK · 11 UNIQUE · 172 CHECK (242 total P/R/U/C)
--
-- Banco
--   Oracle Database 11g+
--
-- Executar como
--   UNMPORTCOM
--------------------------------------------------------------------------------

SET DEFINE OFF
SET SERVEROUTPUT ON
SET LINESIZE 200
SET PAGESIZE 100

PROMPT ==========================================================
PROMPT Portal de Comunicação
PROMPT Validação da Instalação
PROMPT ==========================================================

DEFINE EXPECT_TABLES     = 23
DEFINE EXPECT_SEQUENCES  = 12
DEFINE EXPECT_INDEXES    = 95
DEFINE EXPECT_CONSTRAINTS = 242

COLUMN OBJETO   FORMAT A30
COLUMN ESPERADO FORMAT 999999
COLUMN ENCONTRADO FORMAT 999999
COLUMN STATUS   FORMAT A10

PROMPT.
PROMPT Resumo de objetos:
PROMPT.

SELECT 'TABELAS' AS OBJETO,
       &&EXPECT_TABLES AS ESPERADO,
       (SELECT COUNT(*) FROM USER_TABLES) AS ENCONTRADO,
       CASE WHEN (SELECT COUNT(*) FROM USER_TABLES) = &&EXPECT_TABLES
            THEN 'OK' ELSE 'FALHA' END AS STATUS
  FROM DUAL
UNION ALL
SELECT 'SEQUENCES',
       &&EXPECT_SEQUENCES,
       (SELECT COUNT(*) FROM USER_SEQUENCES),
       CASE WHEN (SELECT COUNT(*) FROM USER_SEQUENCES) = &&EXPECT_SEQUENCES
            THEN 'OK' ELSE 'FALHA' END
  FROM DUAL
UNION ALL
SELECT 'INDICES',
       &&EXPECT_INDEXES,
       (SELECT COUNT(*) FROM USER_INDEXES WHERE INDEX_NAME NOT LIKE 'SYS_%'),
       CASE WHEN (SELECT COUNT(*) FROM USER_INDEXES WHERE INDEX_NAME NOT LIKE 'SYS_%') = &&EXPECT_INDEXES
            THEN 'OK' ELSE 'FALHA' END
  FROM DUAL
UNION ALL
SELECT 'CONSTRAINTS',
       &&EXPECT_CONSTRAINTS,
       (SELECT COUNT(*) FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE IN ('P','R','U','C')),
       CASE WHEN (SELECT COUNT(*) FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE IN ('P','R','U','C')) = &&EXPECT_CONSTRAINTS
            THEN 'OK' ELSE 'FALHA' END
  FROM DUAL
UNION ALL
SELECT 'COMENTARIOS_TABELA',
       &&EXPECT_TABLES,
       (SELECT COUNT(*) FROM USER_TAB_COMMENTS WHERE COMMENTS IS NOT NULL),
       CASE WHEN (SELECT COUNT(*) FROM USER_TAB_COMMENTS WHERE COMMENTS IS NOT NULL) = &&EXPECT_TABLES
            THEN 'OK' ELSE 'FALHA' END
  FROM DUAL
UNION ALL
SELECT 'OBJETOS_INVALIDOS',
       0,
       (SELECT COUNT(*) FROM USER_OBJECTS WHERE STATUS = 'INVALID'),
       CASE WHEN (SELECT COUNT(*) FROM USER_OBJECTS WHERE STATUS = 'INVALID') = 0
            THEN 'OK' ELSE 'FALHA' END
  FROM DUAL;

PROMPT.
PROMPT Tabelas instaladas:
PROMPT.

SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED
  FROM USER_TABLES
 ORDER BY TABLE_NAME;

PROMPT.
PROMPT Sequences instaladas:
PROMPT.

SELECT SEQUENCE_NAME, CACHE_SIZE, LAST_NUMBER
  FROM USER_SEQUENCES
 ORDER BY SEQUENCE_NAME;

PROMPT.
PROMPT Objetos inválidos:
PROMPT.

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE STATUS = 'INVALID'
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

PROMPT.
PROMPT Privilégios da role UNMPORTCOM_APP_ROLE (amostra):
PROMPT.

SELECT TABLE_NAME, PRIVILEGE, COUNT(*) AS QTD
  FROM USER_TAB_PRIVS
 WHERE GRANTEE = 'UNMPORTCOM_APP_ROLE'
 GROUP BY TABLE_NAME, PRIVILEGE
 ORDER BY TABLE_NAME, PRIVILEGE;

PROMPT.
PROMPT ==========================================================
PROMPT Validação concluída.
PROMPT Fim do script 901-validation.sql
PROMPT ==========================================================
PROMPT.
